database:
  host: localhost
  name: maildb
  user: mail
  password: mail

forwardings:
  table: forwardings
  source: source
  destination: destination

users:
  table: users
  email: email
  password: password